name: Automatic Trigger

on:
    push:
      branches:
        - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Run job
      id: run_job
      run: |
        # Run az ml job create command and capture the output in a variable
        output_json=$(az ml job create --file ./src/job.yml --resource-group python-working-group-rg --workspace-name ml-ops-demo)

        # Extract the desired value from the JSON using jq
        path_value=$(echo "$output_json" | jq -r '.id')

        # Set the output variable for later use

        # Poll for Azure Machine Learning run completion
        while true; do
          # Check the status of the run
          status=$(az ml run show --run-id "$path_value" --output json | jq -r '.status')
          echo "AML Run Status: $status"

          # Break the loop if the run is completed
          if [ "$status" == "Completed" ]; then
            break
          fi

          sleep 5  # Add a delay between checks
        done

        echo "::set-output name=path_variable::${path_value}"
        echo "Output [$path_value]"
        
    - name: Deploy model
      run: 
        az ml model create --name MLmodel --path ${{steps.run_job.outputs.path_variable}} --workspace-name ml-ops-demo

# az ml job create --file ./src/job.yml --resource-group python-working-group-rg --workspace-name ml-ops-demo 
# echo "::set-output name=path_variable::${steps.run_job.outputs.path}"