name: Automatic Trigger

on:
    push:
      branches:
        - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Run job
      id: run_job
      run: |
        # Run your az ml job create command and capture the output in a variable

        az ml job create --file ./src/job.yml --resource-group python-working-group-rg --workspace-name ml-ops-demo
        output_json=$(az ml job create --file ./src/job.yml --resource-group python-working-group-rg --workspace-name ml-ops-demo)

        # Extract the desired value from the JSON using jq
        path_value=$(echo "$output_json" | jq -r '.id')

        # Set the output variable for later use
        echo "::set-output name=path_variable::${path_value}"
        echo "Output [$path_value]"
        
    - name: Deploy model
      run: 
        az ml model create --name MLmodel --path ${{steps.run_job.outputs.path_variable}}
        
# az ml job create --file ./src/job.yml --resource-group python-working-group-rg --workspace-name ml-ops-demo 
# echo "::set-output name=path_variable::${steps.run_job.outputs.path}"