name: Run Job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Run job
      id: run_job
      run: |
        # Run az ml job create command and capture the output in a variable
        output_json=$(az ml job create --file ./src/job.yml --resource-group python-working-group-rg --workspace-name ml-ops-demo)
      
        # Extract the desired value from the JSON using jq
        path_value=$(echo "$output_json" | jq -r '.id')

        # Create a file containing the path_value
        echo "path_value=$path_value"  > path_value.txt

        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add path_value.txt
        git commit -m "Update shared variable [skip ci]"
        git push
# save the outputs of the created job to github environment variables

# az ml job create --file ./src/job.yml --resource-group python-working-group-rg --workspace-name ml-ops-demo 
# echo "::set-output name=path_variable::${steps.run_job.outputs.path}"